### ISSUE TITLE
New shows fail instantly due to 404

### ISSUE THREAD

**Issue by sramsay64** [vadmium/python-iview#15]
Downloading new shows fail and 404 (stack trace below). I haven't worked out what date yet but if we use Doctor Who as an example, episodes 1 to 10 will download but episodes 11 and 12 throw 404 errors. I have tried with both frontends and my own frontend. I think this issue is the same as [this issue](https://github.com/sramsay64/python-iview/issues/2). I also think that this maybe due to the new audio description feature since that came in recently and would be some kind of change that affects only new videos. Other things that error include: "Audio Description- A new feature on iview", "The Checkout" and "7:30 Report"

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
        self.run()
      File "/home/scott/bin/python-iview/iview/fetch.py", line 259, in run
        abort=self.abort, **self.kw)
      File "/home/scott/bin/python-iview/iview/fetch.py", line 284, in hds_open_file
        return hds.fetch(*pos, dest_file=dest_file, **kw)
      File "/home/scott/bin/python-iview/iview/hds.py", line 45, in fetch
        manifest = get_manifest(url, session)
      File "/home/scott/bin/python-iview/iview/hds.py", line 530, in get_manifest
        with http_get(session, url, ("video/f4m",)) as response:
      File "/home/scott/bin/python-iview/iview/utils.py", line 218, in http_get
        response = session.open(req)
      File "/usr/lib/python3.4/urllib/request.py", line 461, in open
        response = meth(req, response)
      File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python3.4/urllib/request.py", line 499, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by vadmium** [comment]
I pushed some preliminary changes to a new branch called “redesign”, which hopefully get the basics working again with the “iview-cli” command. It switches from the old (2013 and earlier) web API to the newer (2014) API. It will definitely need more work.

I would be interested if anyone is watching this issue and they are on an unmetered connection, if they can confirm that the new downloads are still unmetered. (I only have a metered connection to test with.)

The trouble with the newer APIs is that they are organized a bit differently to before. My changes so far will have broken compatibility with the functions that the front-ends use. I might be able to smooth things out better, but I’m not sure.

**Comment by iviewadmirer** [comment]
Can confirm this problem.  Have noticed it seems to be for shows with a / in the path, ie kids/anything, whereas shows with no sub-folder typically work.  Just an observation.

**Comment by iviewadmirer** [comment]
Is this the feedback you are looking for, re unmetered: 

host:user$ ./iview-cli -a
iView auth data:
	Streaming Host: AkamaiHDUnmetered
	RTMP Token: daEb_dPaGbhcLaRchd.bjbXahc6ajaVaJdY-bvlV37-8-mnm_tFypM&aifp=v001
	HDS Token: st=1429143035~exp=1429153034~acl=/*~hmac=cfd0ae4fed79ff8b559479079fda6e35d3657a9c551494167541236b8c87d3af
	Server URL: http://iviewum-vh.akamaihd.net/z/
	Playpath Prefix: playback/_definst_/
	Unmetered: True

**Comment by iviewadmirer** [comment]
Installed the "redesign" branch and tried again. Still failing.

<snip>/tools/iview.external/iview-cli -d 'kids/treefutom_01_11.mp4' -o '<snip>/Downloads/Tree Fu Tom.s1e11.Crystal Catastrophe.mp4'
Traceback (most recent call last):
  File "<snip>/iview.external/iview-cli", line 303, in <module>
    main()
  File "<snip>/iview.external/iview-cli", line 292, in main
    download(args.download, args.output)
  File "<snip>/iview.external/iview-cli", line 100, in download
    iview.fetch.fetch_program(url, execvp=True, dest_file=output)
  File "<snip>/iview.external/iview/fetch.py", line 177, in fetch_program
    quiet=quiet, frontend=frontend)
  File "<snip>/iview.external/iview/fetch.py", line 243, in fetch
    key=config.akamaihd_key, **kw)
  File "<snip>/iview.external/iview/fetch.py", line 284, in hds_open_file
    return hds.fetch(*pos, dest_file=dest_file, **kw)
  File "<snip>/iview.external/iview/hds.py", line 45, in fetch
    manifest = get_manifest(url, session)
  File "<snip>/iview.external/iview/hds.py", line 530, in get_manifest
    with http_get(session, url, ("video/f4m",)) as response:
  File "<snip>/iview.external/iview/utils.py", line 218, in http_get
    response = session.open(req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Checking "-a" again with this redesign code:

host:user$ ./iview-cli -a
iView auth data:
	Streaming Host: AkamaiHDUnmetered
	RTMP Token: daEaAblcBdYciaVdacGd5dIcdbZdldia_b.-bvlWaa-8-plm_yHrpN&aifp=v001
	HDS Token: st=1429143552~exp=1429153551~acl=/*~hmac=32c731c64a3b9ba4503ef26d86506282e72ef54eb0f26cefe3522b1b7180b90a
	Server URL: http://iviewum-vh.akamaihd.net/z/
	Playpath Prefix: playback/_definst_/
	Unmetered: True

**Comment by jamver** [comment]
The / in the source path is a red herring.  The following example fails.

  iview-cli -d gardeningaus_26_06.mp4

Just to confirm, the issue (for me on an unmetered Internode connection) is only with downloading, not index or series descriptions.

Older content seems to work, but recently aired or recently added to the streaming server content fails with a 404.  "drwhoconfidential_01_12.mp4" works fine whereas goodgamepocket_01_42.mp4 does not.

I've explicitly tried the hack of setting ip = '22.22.22.22' to force a metered connection, but this does not change the download server.

**Comment by vadmium** [comment]
@iviewadmirer: thanks for trying it out. Unfortunately all the media file names are changed in the new API. Can you try again, throwing away your old file name and starting from scratch:

```
$ ./iview-cli -i
[. . .]
programs/tree-fu-tom/ZW0048A012S00	Tree Fu Tom
[. . .]
$ ./iview-cli -s programs/tree-fu-tom/ZW0048A012S00
Fungus Among Us	(programs/tree-fu-tom/ZW0048A012S00)
Crystal Catastrophe	(programs/tree-fu-tom/ZW0048A011S00)
[. . .]
$ ./iview-cli -d programs/tree-fu-tom/ZW0048A011S00 -o [. . .]
```

BTW with this new API you can also steal the codes from the Iview web site URLs.

**Comment by vadmium** [comment]
Basically I am fairly confident that the above command should download the video for you (if you use the new filename format), but I want to confirm that you are not being metered for it.

**Comment by gdurbrid** [comment]
Thanks, this is working for me, with files which previously I could not download. Oddly, new filenames in the old format are showing up in iview-cli -p but can't be used in iview-cli -d Since my access is metered, I can't help with whether this defeats un-metering.

**Comment by codebje** [comment]
It looks like it's coming through as unmetered for me, using the redesign branch.  --batch doesn't work on that branch, fwiw.

**Comment by sramsay64** [comment]
The `-k` option also doesn't work but I can now download shows again (using the redesign branch). Thanks @vadmium, you can close the issue if you want or just keep it open for more comments about the new branch.

**Comment by ruthtern** [comment]
Just downloaded the redesign branch. Using Internode, downloaded 2GB of iview catchup, confirmed that 2GB appears in the Unmetered Usage column. All is good again. Many thanks.

One minor bug ...
Using "iview-cli -s" to list episodes fails if the program only has a single episode (eg Insiders, Landline). Error text follows ...
Traceback (most recent call last):
  File "/usr/local/bin/iview-cli", line 305, in <module>
    main()
  File "/usr/local/bin/iview-cli", line 289, in main
    series(args.series)
  File "/usr/local/bin/iview-cli", line 73, in series
    [episodes, _] = iview.comm.get_series_items(series_id)
  File "/usr/local/src/python-iview-redesign-20150415/iview/comm.py", line 137, in get_series_items
    for [episode, _] in parser.parse_index_section(others):
  File "/usr/local/src/python-iview-redesign-20150415/iview/parser.py", line 80, in parse_index_section
    for entry in section["episodes"]:
TypeError: tuple indices must be integers, not str

**Comment by vadmium** [comment]
Thanks for the feedback people, it looks like the unmetering is still working properly. I’ll keep this open until I eventually fix the leftover bugs and merge back into the main branch.

To summarize, the only options probably working so far are -i, -s, and -d, and the file/URL names for the episodes are all different.

Some of the bugs remaining are:
* -p doesn’t work. Not sure how to solve this, since the new API doesn’t have a single page that returns everything, and scraping all related pages for each series would probably be really slow. Maybe I will remove this option and add a search option instead.
* -s is broken with programmes that only have one episode available, e.g. Landline
* -k doesn’t work
* batch mode needs fixing
* many other options (e.g. subtitles/captions), iview-gtk, etc probably need fixing too

**Comment by earthnative** [comment]
Is the original -p known incomplete, or fully discontinued soon? Otherwise why not use that to get a listing of what's available, and use the redesign method only when needed? (My home-scripts report on what's newly available by regularly getting an updated program, and diffing against the previous, so losing 'the complete program' functionality would be a major hit for me!)

**Comment by iviewadmirer** [comment]
The old -p also provided program episode descriptions and thumbnail art paths. Is there any mechanism to access that data still?

Thanks for your efforts with this. Even the new abc iview for kids on the iPad which is fabulous is no good for the little ones when we are in the car.

**Comment by vadmium** [comment]
I discovered that they have basically started putting the bitrate in the file names. Old version: `fortitude_01_08.mp4`, new version: `_video/fortitude_01_08_650000.mp4`. And it looks like we can use the Samsung API feed or something to tell which filename format to use, so -p can stay 100% working, etc.

**Comment by vadmium** [comment]
Pushed a change (c0f37a1300) to the master branch that should fix almost everything. The only thing left to do is to fix the subtitles option. So I don’t think the redesign branch is needed for the time being, but maybe in the future if things change again, it might come in handy.

**Comment by gdurbrid** [comment]
Thanks Martin. On a quick test, it is working brilliantly.

**Comment by iviewadmirer** [comment]
Using the latest code from the master branch.

Martin, can you explain the discrepancy between the -p output and the -i & -s output, for the example below I use "Guess With Jess".  -p lists far more episodes (17-47), new naming format.  -i -s lists less (17-36) Thanks.

./iview-cli -p | grep -i guess | grep -i with | grep -i jess
Guess With Jess:
	How Can I Make The Trolley Go Faster?	(_video/kids_guesswithjess_01_47_650000.mp4)
	How Can I Make Kevin The Carp Happy In His Pond?	(_video/kids_guesswithjess_01_45_650000.mp4)
	How Can We Keep Dry For Horace's Concert?	(_video/kids_guesswithjess_01_44_650000.mp4)
	What's The Funny Little Creature In The Pond?	(_video/kids_guesswithjess_01_43_650000.mp4)
	How Can We All Keep Cool?	(_video/kids_guesswithjess_01_42_650000.mp4)
	What's Happening To My Little Tree?	(_video/kids_guesswithjess_01_41_650000.mp4)
	What Hat Should Mimi Wear?	(_video/kids_guesswithjess_01_40_650000.mp4)
	What Shall We Have For Our Harvest Breakfast?	(kids/guesswithjess_01_39.mp4)
	How Can I Go Faster Than Joey And Jinx?	(kids/guesswithjess_01_38.mp4)
	How Can We Hide To Watch Butterflies?	(kids/guesswithjess_01_37.mp4)
	How Can We Help Billy Stay Warm?	(kids/guesswithjess_01_36.mp4)
	How Can I Make My Peach Soft?	(kids/guesswithjess_01_35.mp4)
	What Can I Do With My Nature Collection?	(kids/guesswithjess_01_34.mp4)
	How Can I Go Up And Down On The See-Saw?	(kids/guesswithjess_01_33.mp4)
	How Can I Stop Little Birds Eating The Seeds?	(kids/guesswithjess_01_32.mp4)
	Why Are There So Many Ladybirds?	(kids/guesswithjess_01_31.mp4)
	Why Are There Little Hills In The Orchard?	(kids/guesswithjess_01_30.mp4)
	How Can We Make The Most Beautiful Garden Ever?	(kids/guesswithjess_01_29.mp4)
	Why's Hedgehog Curled Up In A Ball?	(kids/guesswithjess_01_28.mp4)
	What Do We Need To Grow Beans?	(kids/guesswithjess_01_27.mp4)
	When Will The Snow Come?	(kids/guesswithjess_01_26.mp4)
	What's That Grumbly Rumbly Noise?	(kids/guesswithjess_01_25.mp4)
	How Did A Dandelion Seed Get Into Mimi's Garden?	(kids/guesswithjess_01_24.mp4)
	Why Won't My Kite Fly?	(kids/guesswithjess_01_23.mp4)
	How Can We Find Sammy Snail?	(kids/guesswithjess_01_22.mp4)
	How Can We Make Music For Mimi?	(kids/guesswithjess_01_21.mp4)
	Where Have All The Stars Gone?	(kids/guesswithjess_01_20.mp4)
	Where's My Feather Gone?	(kids/guesswithjess_01_19.mp4)
	How Can We Paint The Lily Pad Green?	(kids/guesswithjess_01_18.mp4)
	When Will The Water Come Back?	(kids/guesswithjess_01_17.mp4)

./iview-cli -i | grep -i jess
2490439	Guess With Jess
 ./iview-cli -s 2490439
When Will The Water Come Back?	(kids/guesswithjess_01_17.mp4)
How Can We Paint The Lily Pad Green?	(kids/guesswithjess_01_18.mp4)
Where's My Feather Gone?	(kids/guesswithjess_01_19.mp4)
Where Have All The Stars Gone?	(kids/guesswithjess_01_20.mp4)
How Can We Make Music For Mimi?	(kids/guesswithjess_01_21.mp4)
How Can We Find Sammy Snail?	(kids/guesswithjess_01_22.mp4)
Why Won't My Kite Fly?	(kids/guesswithjess_01_23.mp4)
How Did A Dandelion Seed Get Into Mimi's Garden?	(kids/guesswithjess_01_24.mp4)
What's That Grumbly Rumbly Noise?	(kids/guesswithjess_01_25.mp4)
When Will The Snow Come?	(kids/guesswithjess_01_26.mp4)
What Do We Need To Grow Beans?	(kids/guesswithjess_01_27.mp4)
Why's Hedgehog Curled Up In A Ball?	(kids/guesswithjess_01_28.mp4)
How Can We Make The Most Beautiful Garden Ever?	(kids/guesswithjess_01_29.mp4)
Why Are There Little Hills In The Orchard?	(kids/guesswithjess_01_30.mp4)
Why Are There So Many Ladybirds?	(kids/guesswithjess_01_31.mp4)
How Can I Stop Little Birds Eating The Seeds?	(kids/guesswithjess_01_32.mp4)
How Can I Go Up And Down On The See-Saw?	(kids/guesswithjess_01_33.mp4)
What Can I Do With My Nature Collection?	(kids/guesswithjess_01_34.mp4)
How Can I Make My Peach Soft?	(kids/guesswithjess_01_35.mp4)
How Can We Help Billy Stay Warm?	(kids/guesswithjess_01_36.mp4)

**Comment by vadmium** [comment]
The missing “Guess with Jess” one is a strange one. I use different request URLs for all the programmes vs a single series/season, since it is a 1.6 MB versus 15 kB JSON file to download. But episodes 37+ are missing from the JSON file. It looks like it is present in the Samsung feed (an XML and RSS file rather than JSON). Perhaps I should switch over to it, assuming it is more reliable.

**Comment by ringofyre** [comment]
Was having similar issues with iview-gtk. All fixed now - thanks very much. Confirmed for unmetred on iinet.
iView auth data:
	Streaming Host: AkamaiHDUnmetered
	RTMP Token: daEcScUasdHdoaGaDbvaxdBdKbRata2aedQ-bvncyV-8-nmr_zHuqJ&aifp=v001
	HDS Token: st=1429481007~exp=1429491006~acl=/*~hmac=8ac498c0e5f37f7acde21a9a1d553f098d520c39ec78f8828cb6dfe886e23c31
	Server URL: http://iviewum-vh.akamaihd.net/z/
	Playpath Prefix: playback/_definst_/
	Unmetered: True

**Comment by rodcloud** [comment]
The following comments refer to Commit: 997dafc49abcd0a4387bea67f685bce6fcd292d0 - "Set episode title to series title for stand-alone programmes ":

* 1. Works well for me on unmetered:
-------------------
iView auth data:
        Streaming Host: AkamaiHDUnmetered
        RTMP Token: daEd9bGaSaacvbJbWbyaOa_b1c.b2d.bJb7-bvnhHS-8-kln_vErpG&aifp=v001
        HDS Token: st=1429502060~exp=1429512059~acl=/*~hmac=4eb8ccbfdb2ac0e1885468ec372e7c5b31012c958b86f6aa99ee1cd8f2e235d9
        Server URL: http://iviewum-vh.akamaihd.net/z/
        Playpath Prefix: playback/_definst_/
        Unmetered: True
-------------------
* 2. The command; "iview-cli -p"  also works.  It gives the correct filename output - for example the snippet below:
-------------------
Doctor Who:
        Series 1 Episode 13 The Parting Of The Ways     (_video/drwhohuman_01_13_650000.mp4)
        Series 1 Episode 12 Bad Wolf    (_video/drwhohuman_01_12_650000.mp4)
        Series 1 Episode 11 Boom Town   (_video/drwhohuman_01_11_650000.mp4)
        Series 1 Episode 10 The Doctor Dances   (drwhohuman_01_10.mp4)
        Series 1 Episode 9 The Empty Child      (drwhohuman_01_09.mp4)
        Series 1 Episode 8 Father's Day (drwhohuman_01_08.mp4)
        Series 1 Episode 7 The Long Game        (drwhohuman_01_07.mp4)
        Series 1 Episode 6 Dalek        (drwhohuman_01_06.mp4)
Doctor Who:
-------------------
* 3. Downloads have been 100% successful so far.  I've found that the old format filenames and the new format filenames (as according to "iview-cli -p"), are both downloading to completion successfully.
* 4. Files all played successfully.

**Comment by jamver** [comment]
Interestingly, the commit mentioned above almost entirely restores the original behaviour with only the addition of a the additional field after the episode number.

**Comment by miriam-e** [comment]
Thank you so much. I can confirm it works on my machine too. Way out in the Queensland bush on satellite internet too slow to stream the shows and unable to receive free-to-air TV here. The only way I can watch ABC TV is via your wonderful code. I'm eternally grateful!

Now, being nearly deaf, I would love for the subtitles to be working again.... please? (I feel a little guilty asking and should really learn python properly so I can delve into the code and help.)

**Comment by miriam-e** [comment]
Maybe I can be of some help with the subtitles. I use Linux bash a lot and have written a short bit of code that successfully gets the subtitles:

		# target is the iview filename like "_video/metalevolution_01_06_650000.mp4"
		# remove the '.mp4' extension
		sub1="${target%.*}"
		# remove the '_video/' prefix
		sub2="${sub1##*/}"
		# remove the bitrate(?) suffix
		sub3="${sub2%_*}"
		# download the xml file and record whether it succeeded or not (endval)
		wget "http://iview.abc.net.au/cc/${sub3}.xml"
		endval=$?
		# if it succeeded...
		if [ "$endval" = "0" ]; then
			xmlfile="${sub3}.xml"
			subfile="${sub3}.srt"
			count="1"
			# convert xmlfile
			cat "$xmlfile" |
			(
				while read line
				do
					if [ "${line:0:7}" = "<title " ]; then
						echo "$count" >>"$subfile"
						echo "$line" | \
						  sed 's/<title start="\([^"]*\)" end="\([^"]*\)">\(.*\)<\/title>/\1 --> \2\n\3/' | \
						  sed 's/|/\n/g' >>"$subfile"
						echo  >>"$subfile"
						let count++
					fi
				done
			)
			# fix slight incompatibility in seconds format
			sed -i 's/:\([0-9][0-9]\) -/,\10 -/' "$subfile"
			sed -i 's/:\([0-9][0-9]\)$/,\10/' "$subfile"
			rm "$xmlfile"
		fi

		# report success or failure
		succeed_fail $endval

The "succeed_fail" function is a simple thing I use to play a sound and print a message that notifies me whether it succeeded or failed -- a nice blip sound if it succeeds; a clang sound if it fails. This is so I can be doing other things (e.g. writing or drawing or programming or cooking and hear how it's managing).

**Comment by vadmium** [comment]
Main issue was fixed and we now have #20 to track the subtitles problem (@miriam-e it also suggests a clever workaround).
